### ISSUE TITLE
Deploying a k8s service with loadbalancer fails

### ISSUE THREAD

**Issue by helgifeiti** [Azure/vm-scale-sets#55]
Hello,

I've deployed a Azure VM scale set successfully, running k8s v1.10.3 with a master scale set and node scale set with 3 workers in the same resource group. 
I deployed an application to it using a Helm chart and everything works except the service with the loadbalancer, which I'm using to expose the app. 
Deploying the service with the loadbalancer sends the kube-controller-manager in a CrashLoopBackOff caused by a fail in azure_vmss.go:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x21f7026]

goroutine 1446 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x30c3980, 0x5642750)
	/usr/local/go/src/runtime/panic.go:491 +0x283
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.(*scaleSet).EnsureHostsInPool(0xc4206a0600, 0xc422a0b100, 0x1b, 0xc420089880, 0x4, 0x4, 0xc420bafc30, 0xa1, 0x0, 0x0, ...)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_vmss.go:563 +0x2b6
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.(*Cloud).reconcileLoadBalancer(0xc42036e400, 0x37c3086, 0xa, 0xc4223be960, 0xc420089880, 0x4, 0x4, 0x1, 0xc4224e8fa0, 0x0, ...)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go:797 +0x3fc3
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.(*Cloud).EnsureLoadBalancer(0xc42036e400, 0x5476140, 0xc42001a030, 0x37c3086, 0xa, 0xc4223be960, 0xc420089880, 0x4, 0x4, 0x5661560, ...)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go:112 +0x2af
k8s.io/kubernetes/pkg/controller/service.(*ServiceController).ensureLoadBalancer(0xc4209f2a80, 0xc4223be960, 0xc4223be960, 0x37bb9a1, 0x6)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:374 +0xe8
k8s.io/kubernetes/pkg/controller/service.(*ServiceController).createLoadBalancerIfNeeded(0xc4209f2a80, 0xc420a7e760, 0x1b, 0xc4223be960, 0xc422584028, 0xc422377cc0)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:305 +0x20e
k8s.io/kubernetes/pkg/controller/service.(*ServiceController).processServiceUpdate(0xc4209f2a80, 0xc422d2a828, 0xc4223be960, 0xc420a7e760, 0x1b, 0x0, 0x0)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:252 +0xe9
k8s.io/kubernetes/pkg/controller/service.(*ServiceController).syncService(0xc4209f2a80, 0xc420a7e760, 0x1b, 0x0, 0x0)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:732 +0x30d
k8s.io/kubernetes/pkg/controller/service.(*ServiceController).processNextWorkItem(0xc4209f2a80, 0x633f00)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:213 +0xe1
k8s.io/kubernetes/pkg/controller/service.(*ServiceController).worker(0xc4209f2a80)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:202 +0x2b
k8s.io/kubernetes/pkg/controller/service.(*ServiceController).(k8s.io/kubernetes/pkg/controller/service.worker)-fm()
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:191 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42253dac0)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42253dac0, 0x3b9aca00, 0x0, 0x1, 0xc42005c480)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42253dac0, 0x3b9aca00, 0xc42005c480)
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/pkg/controller/service.(*ServiceController).Run
	/workspace/anago-v1.10.2-beta.0.102+81753b10df1129/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:191 +0x20c
```

I see the loadbalancer and public IP address for it  get created in the Portal, but I noticed the loadbalancer is created with a backendpool only associated with the loadbalancer rule, with no `Target network IP configurations` specified, like in an AKS with a deployed k8s app. This is what I thought might be causing the crash in the `EnsureHostsInPool` function in azure_vmss.go. However, I can't do any manual associations (as both the master vmss and node are already associated with their own loadbalancer) and also, unlike the AKS the VMSS does not have an availability set, which is also associated with the backend pool in the AKS deployment. 

Could this be a problem with the configuration of my VMSS or are they not able to handle k8s services with loadbalancers, since they already have loadbalancers created with each scale set? And if so, is there another way to expose the app?

**Comment by helgifeiti** [comment]
#Close 55
